# Go dynamically overwrites this file completely
# [idp_target]
# i-0e83c42f109e75c95 ansible_host=3.133.100.123 ansible_user=ubuntu 

[idp_target]
ansibletime ansible_host=i-0e83c42f109e75c95 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

#this is an example and should be completely blank