# Go was going to dynamically overwrites this file completely; so this is just an example output using EC2 id, ip, username
# In testing, needed a default ssh keypair for local machine to think it was in use for connection
# Ansible was fine using AWS SSM to connect to the EC2, but local linux machine got angry about that

[idp_target]
i-0e83c42f109e75c95 ansible_host=3.133.100.123 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa